param(
  [string]$Source = "site/assets/us-map-source.svg",
  [string]$Output = "site/assets/us-state-map-paths.mjs"
)

$ErrorActionPreference = "Stop"
[xml]$document = Get-Content -LiteralPath $Source -Raw
$viewBox = [string]$document.svg.viewBox
$paths = @(
  $document.SelectNodes("//*[local-name()='path']") |
    Where-Object { $_.id -match "^[A-Z]{2}$" } |
    Sort-Object id
)

if ($viewBox -ne "0 0 1000 589") {
  throw "Unexpected map viewBox: $viewBox"
}
if ($paths.Count -ne 51) {
  throw "Expected 51 state and District paths; received $($paths.Count)."
}
if (-not ($paths.id -contains "DC")) {
  throw "The supplied map is missing the District of Columbia path."
}

$entries = $paths | ForEach-Object {
  "  $($_.id): $([string]$_.d | ConvertTo-Json -Compress),"
}
$lines = @(
  "// Geometry extracted from Simplemaps us.svg (commercial-use source notice retained in us-map-source.svg)."
  "// Generated by site/scripts/generate-us-state-map-paths.ps1; do not hand-edit path data."
  "export const US_MAP_VIEWBOX = $($viewBox | ConvertTo-Json -Compress);"
  "export const US_STATE_PATHS = {"
  $entries
  "};"
  ""
  'export const DC_STAR = "M880 220 L883 227 L891 227 L885 232 L887 240 L880 236 L873 240 L875 232 L869 227 L877 227 Z";'
)

$outputPath = [IO.Path]::GetFullPath((Join-Path (Get-Location) $Output))
$utf8 = New-Object Text.UTF8Encoding($false)
[IO.File]::WriteAllText($outputPath, ($lines -join [Environment]::NewLine) + [Environment]::NewLine, $utf8)
Write-Output "Generated $Output from $($paths.Count) state paths."
